encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path('', views.index, name='index'),
    path('wiki/<str:title>', views.article, name='article'),
    path('search/', views.search, name='search'),
    path('create/', views.create_article, name='create'),
    path('edit/<str:title>', views.edit_article, name='edit'),
    path('random/', views.random_article, name='random'),
    path('404/', views.custom_not_found_view, name='404'),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('encyclopedia.urls')), 
]

handler404 = 'encyclopedia.views.custom_not_found_view'

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django import forms
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect
# from django.core.exceptions import ValidationError

from . import util


class NewArticleForm(forms.Form):
    title = forms.CharField(label='Title')
    content = forms.CharField(widget=forms.Textarea)

    # First error validation, that I find on Internet
    # def clean_title(self):
    #     title = self.cleaned_data['title'] 
    #
    #     if title in util.list_entries():
    #        raise ValidationError('The article already exists!')
    # 
    #     return title


def index(request):
    return render(request, 'encyclopedia/index.html', {
        'entries': util.list_entries()
    })


def article(request, title):
    import markdown2

    if (not title.upper() in (
        entry.upper() for entry in util.list_entries()
    )):
        return render(request, 'encyclopedia/page_does_not_exists.html')
        

    for entry in util.list_entries():
        if entry.upper() == title.upper():
            title = entry
            break

    if request.path.split('/')[2].upper() == title.upper():
        return render(request, 'encyclopedia/article.html', {
            'title': title,
            'content': markdown2.markdown(util.get_entry(title)),
        })


def search(request):
    query = request.GET.get('q')
    
    if query in util.list_entries():
        return HttpResponseRedirect(reverse('encyclopedia:article', args=(query,)))
   
    return render(request, 'encyclopedia/index.html', {
        'entries': [entry for entry in util.list_entries() if query.upper() in entry.upper()] 
    })


def create_article(request):
    if request.method == 'POST':
        form = NewArticleForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']

            # Second error validation
            if title in util.list_entries():
                form.add_error('title', 'The article already exists!')

                return render(request, 'encyclopedia/create_article.html', {
                    'form': form
                })

            util.save_entry(title, content)
            
            return HttpResponseRedirect(reverse('encyclopedia:article', args=(title,))) 
    
    return render(request, 'encyclopedia/create_article.html', {
        'form': NewArticleForm()
    })


def edit_article(request, title):
    content = util.get_entry(title)
 
    if request.method == 'POST':
        form = NewArticleForm(request.POST)

        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']

            util.save_entry(title, content)

            return HttpResponseRedirect(reverse('encyclopedia:article', args=(title,)))
        else:
            return render(request, 'encyclopedia/edit_article.html', {
                'title': title,
                'form': form
            })

    return render(request, 'encyclopedia/edit_article.html', {
        'title': title,
        'form': NewArticleForm({ 'content': content }) 
    })


def random_article(request):
    import random

    entries = util.list_entries()

    if entries:
        random_entry = random.choice(entries)

        return HttpResponseRedirect(reverse('encyclopedia:article', args=(random_entry,))) 


def custom_not_found_view(request, exception):
    title = request.path.split('/')[1]

    return render(request, 'encyclopedia/404.html', {
        'title': title,
    })

encyclopedia/templates/encyclopedia/article.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
    <p>{{ content | safe }}</p>

    <a href="{% url 'encyclopedia:edit' title %}">Edit article</a>
{% endblock %}

encyclopedia/templates/encyclopedia/create_article.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Create article{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:create' %}" method="POST">
        {% csrf_token %}

        {{ form.as_div }}

        <input type="submit" value="Submit" />
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit_article.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Edit {{ title }}{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    <form action="{% url 'encyclopedia:edit' title %}" method="POST">
        {% csrf_token %}

        <input type="hidden" name='title' value="{{ title }}" id="id_title" required />
    
        {{ form.content }}

        <input type="submit" value="Submit" />
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:article' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title%}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
        crossorigin="anonymous" />
        <link href="{% static 'encyclopedia/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <div class="row w-100">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>

                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" />
                </form>

                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>

                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/page_does_not_exists.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Does Not Exists{% endblock %}

{% block body %}
    <h1>Article Does Not Exists</h1>

    <p>If you want to create <a href="{% url 'encyclopedia:create' %}">PRESS THIS</a>.</p>
    <p>If you mistakes with url <a href="{% url 'encyclopedia:index' %}">PRESS THIS</a> redirect to MAIN PAGE.</p>
{% endblock%}